services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventario_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mi-postgres:5432/inventarioicvcsistemas
      SPRING_DATASOURCE_USERNAME: sistemasicvc
      SPRING_DATASOURCE_PASSWORD: icvc2024
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    networks:
      - red_icvc

networks:
  red_icvc:
    external: true
