spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventarioicvcsistemas?currentSchema=public
    username: sistemasicvc
    password: icvc2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
        hbm2ddl:
          auto: none
        jdbc:
          lob:
            non_contextual_creation: true
        generate_statistics: true
        use_sql_comments: true
      open-in-view: false
